import { parseCommandArgs, UsageError } from "../cli-args.js";
import {
  ANNOTATE_FLAGS,
  COMPLETION_SHELLS,
  GLOBAL_FLAGS,
  LIST_LIKE_FLAGS,
  PUT_LIKE_FLAGS,
  SCREENSHOT_FLAGS,
  ROOT_COMMANDS,
  isCompletionShell,
  type CompletionShell,
} from "../cli-catalog.js";
import { writeCommandHelp } from "../cli-style.js";

const HELP = `uploads completion <shell>

Print a shell completion script to stdout. Save it where your shell looks for
completions, then start a new shell. Tab then completes commands, subcommands,
and common flags.

Shells:
  bash   Bash (complete -F)
  zsh    Zsh (#compdef)
  fish   Fish (complete -c)

Examples:
  # bash — for the current session:
  eval "$(uploads completion bash)"
  # or save it:
  uploads completion bash > ~/.local/share/bash-completion/completions/uploads

  # fish
  uploads completion fish > ~/.config/fish/completions/uploads.fish

  # zsh — save the script:
  uploads completion zsh > ~/.zsh/completions/_uploads
  # then add these two lines to the END of ~/.zshrc:
  #   fpath=(~/.zsh/completions $fpath)
  #   autoload -Uz _uploads && compdef _uploads uploads

Zsh notes:
  Saving the file into an fpath directory is often not enough. compinit caches
  its scan in ~/.zcompdump, and \`compinit -C\` reuses that cache instead of
  rescanning, so it never sees the new file. Oh My Zsh and several installers
  call compinit that way. Some plugins also rewrite fpath as they load, which
  drops entries added before them; zsh-autocomplete is one.

  The \`compdef\` line avoids both problems, because it binds the function
  directly instead of relying on a scan. Put it after any framework or plugin
  setup. If completion still does nothing, delete ~/.zcompdump* and start a
  new shell.

  Check the result with: print $_comps[uploads] — it prints _uploads when the
  completion is active, and nothing when it is not.

After you upgrade the CLI, generate the script again so it lists new commands.
`;

function bashScript(): string {
  const cmds = ROOT_COMMANDS.map((c) => c.name).join(" ");
  const globals = GLOBAL_FLAGS.map((g) => g.flag).join(" ");
  const putFlags = PUT_LIKE_FLAGS.join(" ");
  const listFlags = LIST_LIKE_FLAGS.join(" ");
  const screenshotFlags = SCREENSHOT_FLAGS.join(" ");
  const annotateFlags = ANNOTATE_FLAGS.join(" ");

  const subMaps = ROOT_COMMANDS.filter((c) => c.subcommands?.length).map((c) => {
    const names = c.subcommands!.map((s) => s.name).join(" ");
    return `    ${c.name}) subs="${names}" ;;`;
  });

  // Shell `$var` / `$(…)` must not be JS-escaped (`\$`); only shell `${…}` needs `\${…}`
  // so the template literal doesn't treat it as interpolation.
  return `# uploads bash completion — generated by: uploads completion bash
# shellcheck shell=bash disable=SC2207

_uploads() {
  local cur prev words cword
  if declare -F _init_completion >/dev/null 2>&1; then
    _init_completion -n : || return
  else
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    words=("\${COMP_WORDS[@]}")
    cword=\${COMP_CWORD}
  fi

  local -a root_cmds=(${cmds})
  local -a globals=(${globals})
  local -a put_flags=(${putFlags})
  local -a list_flags=(${listFlags})
  local -a screenshot_flags=(${screenshotFlags})
  local -a annotate_flags=(${annotateFlags})

  # Find the first non-global positional (the subcommand).
  local cmd="" i=1
  while [[ $i -lt $cword ]]; do
    local w="\${words[i]}"
    case "$w" in
      --api-url|--token|--workspace|-w|--env-file)
        i=$((i + 2))
        continue
        ;;
      --json|--quiet|--version|-V|--help|-h|--all)
        i=$((i + 1))
        continue
        ;;
      -*)
        i=$((i + 1))
        continue
        ;;
      *)
        cmd="$w"
        break
        ;;
    esac
  done

  if [[ -z "$cmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "\${globals[*]}" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "\${root_cmds[*]}" -- "$cur") )
    fi
    return
  fi

  local subs=""
  case "$cmd" in
${subMaps.join("\n")}
  esac

  # Completing the subcommand word (or first arg after command).
  if [[ "$prev" == "$cmd" && -n "$subs" ]]; then
    COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    return
  fi

  if [[ "$cur" == -* ]]; then
    case "$cmd" in
      put)
        COMPREPLY=( $(compgen -W "\${put_flags[*]} --url" -- "$cur") )
        ;;
      attach)
        COMPREPLY=( $(compgen -W "\${put_flags[*]}" -- "$cur") )
        ;;
      screenshot)
        COMPREPLY=( $(compgen -W "\${screenshot_flags[*]}" -- "$cur") )
        ;;
      annotate)
        COMPREPLY=( $(compgen -W "\${annotate_flags[*]}" -- "$cur") )
        ;;
      list|find)
        COMPREPLY=( $(compgen -W "\${list_flags[*]}" -- "$cur") )
        ;;
      *)
        COMPREPLY=( $(compgen -W "--help -h --workspace -w --json --quiet" -- "$cur") )
        ;;
    esac
    return
  fi

  # File paths for upload-style commands.
  case "$cmd" in
    put|attach|screenshot|annotate)
      COMPREPLY=( $(compgen -f -- "$cur") )
      ;;
  esac
}

complete -o default -F _uploads uploads
`;
}

function zshScript(): string {
  const cmdDescribe = ROOT_COMMANDS.map((c) => {
    const desc = c.summary.replace(/'/g, "'\\''");
    return `    '${c.name}:${desc}'`;
  }).join("\n");

  const globalArgs = GLOBAL_FLAGS.map((g) => {
    const desc = g.summary.replace(/'/g, "'\\''");
    // Pair each short flag with its long form, keeping the long form's cleaner
    // summary; the short entry then contributes nothing of its own.
    if (g.flag === "--workspace")
      return `    '(-w --workspace)'{-w,--workspace}'[${desc}]:workspace:'`;
    if (g.flag === "-w") return null; // paired with --workspace
    if (g.flag === "--version") return `    '(-V --version)'{-V,--version}'[${desc}]'`;
    if (g.flag === "-V") return null;
    if (g.flag === "--help") return `    '(-h --help)'{-h,--help}'[${desc}]'`;
    if (g.flag === "-h") return null;
    if (g.flag === "--api-url") return `    '--api-url[${desc}]:url:'`;
    if (g.flag === "--token") return `    '--token[${desc}]:token:'`;
    if (g.flag === "--env-file") return `    '--env-file[${desc}]:file:_files'`;
    return `    '${g.flag}[${desc}]'`;
  })
    .filter(Boolean)
    // Every spec but the last needs a line continuation — without them zsh ends
    // the `_arguments` call after the first spec and tries to *run* the rest.
    .join(" \\\n");

  const subCases = ROOT_COMMANDS.filter((c) => c.subcommands?.length)
    .map((c) => {
      const lines = c
        .subcommands!.map((s) => {
          const desc = s.summary.replace(/'/g, "'\\''");
          return `          '${s.name}:${desc}'`;
        })
        .join("\n");
      return `      ${c.name})
        local -a subs
        subs=(
${lines}
        )
        _describe 'subcommand' subs
        ;;`;
    })
    .join("\n");

  return `#compdef uploads
# uploads zsh completion — generated by: uploads completion zsh

_uploads() {
  local -a commands
  commands=(
${cmdDescribe}
  )

  local context state state_descr line
  typeset -A opt_args

  _arguments -C -s -S \\
${globalArgs} \\
    '1:command:->cmds' \\
    '*::arg:->args'

  case $state in
    cmds)
      _describe -t commands 'uploads command' commands
      ;;
    args)
      case $line[1] in
${subCases}
      put|attach|screenshot|annotate)
        _files
        ;;
      esac
      ;;
  esac
}

_uploads "$@"
`;
}

function fishScript(): string {
  const lines: string[] = [
    `# uploads fish completion — generated by: uploads completion fish`,
    `complete -c uploads -e`,
    `complete -c uploads -f`,
  ];

  for (const g of GLOBAL_FLAGS) {
    const short = g.flag.length === 2 && g.flag.startsWith("-") && !g.flag.startsWith("--");
    if (short) {
      // Pair handled with long form when possible
      continue;
    }
    const esc = g.summary.replace(/'/g, "\\'");
    if (g.flag === "--workspace") {
      lines.push(`complete -c uploads -s w -l workspace -d '${esc}' -r`);
    } else if (g.flag === "--version") {
      lines.push(`complete -c uploads -s V -l version -d '${esc}'`);
    } else if (g.flag === "--help") {
      lines.push(`complete -c uploads -s h -l help -d '${esc}'`);
    } else if (g.flag === "--api-url" || g.flag === "--token" || g.flag === "--env-file") {
      lines.push(`complete -c uploads -l ${g.flag.slice(2)} -d '${esc}' -r`);
    } else {
      lines.push(`complete -c uploads -l ${g.flag.slice(2)} -d '${esc}'`);
    }
  }

  for (const c of ROOT_COMMANDS) {
    const esc = c.summary.replace(/'/g, "\\'");
    lines.push(`complete -c uploads -n '__fish_use_subcommand' -a '${c.name}' -d '${esc}'`);
    if (c.subcommands?.length) {
      for (const s of c.subcommands) {
        const sEsc = s.summary.replace(/'/g, "\\'");
        // --all under help is a flag-like token; fish still accepts it as -a
        lines.push(
          `complete -c uploads -n '__fish_seen_subcommand_from ${c.name}' -a '${s.name}' -d '${sEsc}'`,
        );
      }
    }
  }

  for (const flag of PUT_LIKE_FLAGS) {
    if (!flag.startsWith("--")) continue;
    lines.push(
      `complete -c uploads -n '__fish_seen_subcommand_from put attach' -l ${flag.slice(2)}`,
    );
  }
  lines.push(`complete -c uploads -n '__fish_seen_subcommand_from put' -l url`);
  for (const flag of SCREENSHOT_FLAGS) {
    if (!flag.startsWith("--")) continue;
    lines.push(
      `complete -c uploads -n '__fish_seen_subcommand_from screenshot' -l ${flag.slice(2)}`,
    );
  }
  for (const flag of LIST_LIKE_FLAGS) {
    if (!flag.startsWith("--")) continue;
    lines.push(
      `complete -c uploads -n '__fish_seen_subcommand_from list find' -l ${flag.slice(2)}`,
    );
  }
  for (const flag of ANNOTATE_FLAGS) {
    if (flag === "-o") continue; // folded into --out's paired completion below
    if (flag === "--out") {
      lines.push(`complete -c uploads -n '__fish_seen_subcommand_from annotate' -s o -l out`);
      continue;
    }
    if (!flag.startsWith("--")) continue;
    lines.push(`complete -c uploads -n '__fish_seen_subcommand_from annotate' -l ${flag.slice(2)}`);
  }

  // File completion for put/attach/screenshot/annotate
  lines.push(
    `complete -c uploads -n '__fish_seen_subcommand_from put attach screenshot annotate' -F`,
  );

  return lines.join("\n") + "\n";
}

export function generateCompletionScript(shell: CompletionShell): string {
  switch (shell) {
    case "bash":
      return bashScript();
    case "zsh":
      return zshScript();
    case "fish":
      return fishScript();
  }
}

export async function runCompletion(args: string[], help = false): Promise<number> {
  const parsed = parseCommandArgs(args);
  if (help || parsed.help || parsed.positionals.length === 0) {
    writeCommandHelp(HELP);
    return help || parsed.help ? 0 : 2;
  }

  const shell = parsed.positionals[0]?.toLowerCase() ?? "";
  if (!isCompletionShell(shell)) {
    throw new UsageError(
      `unknown shell: ${parsed.positionals[0]} (expected ${COMPLETION_SHELLS.join(", ")})`,
    );
  }

  process.stdout.write(generateCompletionScript(shell));
  return 0;
}
