#!/usr/bin/env node
/**
 * Inline private workspace packages into the published CLI source.
 *
 * The CLI tarball cannot depend on @uploads/* (those packages are private).
 * This script copies the canonical modules into packages/uploads/src/*.generated.ts
 * so `tsc` emits self-contained JS/d.ts. Run without flags to write; --check
 * exits 1 if a generated file is stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const cliRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(cliRoot, "..", "..");
const check = process.argv.includes("--check");

const HEADER = `/**
 * GENERATED by packages/uploads/scripts/inline-shared.mjs — do not edit.
 * Canonical source: {{source}}
 * The published CLI cannot import private @uploads/* packages, so this file
 * is inlined into the tarball. Re-run the script after changing the source.
 */

`;

const copies = [
  {
    source: "packages/github-comment/src/index.ts",
    dest: "packages/uploads/src/github-comment.generated.ts",
  },
  {
    source: "packages/comment-config/src/index.ts",
    dest: "packages/uploads/src/comment-config.generated.ts",
  },
];

let stale = false;
for (const { source, dest } of copies) {
  const raw = readFileSync(join(repoRoot, source), "utf8");
  // Drop the canonical file's leading doc-comment so we don't nest two headers.
  const body = raw.replace(/^\/\*\*[\s\S]*?\*\/\s*/, "");
  const next = HEADER.replace("{{source}}", source) + body;
  const destPath = join(repoRoot, dest);
  if (check) {
    let current = "";
    try {
      current = readFileSync(destPath, "utf8");
    } catch {
      current = "";
    }
    if (current !== next) {
      console.error(
        `stale generated copy: ${dest} (run node packages/uploads/scripts/inline-shared.mjs)`,
      );
      stale = true;
    }
    continue;
  }
  writeFileSync(destPath, next);
  console.log(`wrote ${dest}`);
}

if (check && stale) process.exit(1);
if (check) console.log("generated CLI copies are up to date");
