export { inferContentType, buildMarkdown } from "./embed.js";
export { sanitizeKeySegment, sha256Short, deriveRepoFromGit, buildScreenshotKey } from "./keys.js";
export {
  BUILTIN_DESTINATIONS,
  isBuiltinDestination,
  keyMatchesDestination,
  resolveDestinationRoot,
  resolvePutPrefix,
  type BuiltinDestinationId,
} from "./destinations.js";
export {
  DEFAULT_API_URL,
  DEFAULT_WORKSPACE,
  UPLOADS_CONFIG_KEYS,
  defaultConfigPath,
  resolveConfigPath,
  loadConfigFile,
  loadEnvFile,
  resolveApiUrl,
  resolveConfig,
  describeConfigSources,
  redactToken,
  writeConfigKeys,
  configValuesFromClient,
  putDefaultsToConfigValues,
  resolvePutDefaults,
  mergePutDefaults,
  workspaceFromToken,
  workspaceMismatch,
  type UploadsClientConfig,
  type ResolvedConfig,
  type WorkspaceSource,
  type ConfigValueSource,
  type ConfigSources,
  type UploadsConfigKey,
  type UploadsConfigValues,
  type PutDefaults,
} from "./config.js";
export { UploadsError, type UploadsErrorCode } from "./errors.js";
export {
  createUploadsClient,
  type UploadsClient,
  type PutOptions,
  type ListOptions,
  type PutResult,
  type ListItem,
  type ListResult,
  type HeadResult,
  type DeleteResult,
  type HealthResult,
  type UsageResult,
  type ReconcileResult,
  type PurgeExpiredResult,
  type PurgeExpiredResponse,
} from "./client.js";
export {
  ATTACHMENTS_MARKER,
  attachmentsCommentBody,
  ghAttachmentKey,
  ghKeyPrefix,
  isValidRepo,
  parseRepoFromRemoteUrl,
  type AttachmentItem,
  type GhTarget,
  type GhTargetKind,
} from "./github.js";
export {
  DEFAULT_OPTIMIZE_MAX_EDGE,
  DEFAULT_OPTIMIZE_QUALITY,
  optimizeImageForUpload,
  rewriteKeyExtension,
  withImageExtension,
  type OptimizeImageOptions,
  type OptimizeImageResult,
  type OptimizeOutputFormat,
} from "./optimize.js";
export {
  execRunner,
  resolveRepo,
  upsertAttachmentsComment,
  type CommandRunner,
} from "./github-gh.js";
