export { inferContentType, buildMarkdown } from "./embed.js";
export {
  DEFAULT_EMBED_PUBLIC_BASE_URL,
  embedBaseUrlFromEnv,
  embedUrlFromPublic,
  resolveEmbedBaseUrl,
  resolveEmbedUrl,
  urlForGithubEmbed,
} from "./public-urls.js";
export { sanitizeKeySegment, sha256Short, deriveRepoFromGit, buildScreenshotKey } from "./keys.js";
export {
  BUILTIN_DESTINATIONS,
  isBuiltinDestination,
  keyMatchesDestination,
  resolveDestinationRoot,
  resolvePutPrefix,
  type BuiltinDestinationId,
} from "./destinations.js";
export {
  DEFAULT_API_URL,
  DEFAULT_WORKSPACE,
  UPLOADS_CONFIG_KEYS,
  defaultConfigPath,
  resolveConfigPath,
  loadConfigFile,
  loadEnvFile,
  resolveApiUrl,
  resolveConfig,
  describeConfigSources,
  redactToken,
  writeConfigKeys,
  configValuesFromClient,
  putDefaultsToConfigValues,
  resolvePutDefaults,
  mergePutDefaults,
  workspaceFromToken,
  workspaceMismatch,
  type UploadsClientConfig,
  type ResolvedConfig,
  type WorkspaceSource,
  type ConfigValueSource,
  type ConfigSources,
  type UploadsConfigKey,
  type UploadsConfigValues,
  type PutDefaults,
} from "./config.js";
export { UploadsError, type UploadsErrorCode } from "./errors.js";
export {
  createUploadsClient,
  type UploadsClient,
  type PutOptions,
  type ProvenanceInput,
  type ListOptions,
  type PutResult,
  type ListItem,
  type ListResult,
  type HeadResult,
  type DeleteResult,
  type GalleryItem,
  type Gallery,
  type GallerySummary,
  type GalleryListOptions,
  type GalleryListResult,
  type CreateGalleryOptions,
  type AddGalleryItemOptions,
  type DeleteGalleryOptions,
  type HealthResult,
  type UsageResult,
  type ReconcileResult,
  type PurgeExpiredResult,
  type PurgeExpiredResponse,
  type FindFilesOptions,
  type FindFilesItem,
  type FindFilesResult,
  type GetMetadataResult,
  type PatchMetadataOptions,
} from "./client.js";
export { buildCliProvenance } from "./provenance.js";
export {
  META_KEY_RE,
  META_VALUE_MAX,
  META_MAX_KEYS,
  META_MAX_TOTAL_BYTES,
  validateMetaEntry,
  parseMetaPair,
  parseMetaFlags,
} from "./metadata.js";
export {
  ATTACHMENTS_MARKER,
  attachmentsCommentBody,
  ghAttachmentKey,
  ghKeyPrefix,
  ghMetadataFromTarget,
  isValidRepo,
  parseRepoFromRemoteUrl,
  type AttachmentItem,
  type GhTarget,
  type GhTargetKind,
} from "./github.js";
export {
  DEFAULT_OPTIMIZE_MAX_EDGE,
  DEFAULT_OPTIMIZE_QUALITY,
  optimizeImageForUpload,
  rewriteKeyExtension,
  withImageExtension,
  type OptimizeImageOptions,
  type OptimizeImageResult,
  type OptimizeOutputFormat,
} from "./optimize.js";
export {
  FRAME_PRESETS,
  applyFrame,
  listFramePresets,
  resolveFrameId,
  type FrameFit,
  type FrameOptions,
  type FrameResult,
} from "./frame.js";
export {
  execRunner,
  resolveRepo,
  upsertAttachmentsComment,
  type CommandRunner,
} from "./github-gh.js";
