// ADMIN_TOKEN is a runtime Worker secret (see .dev.vars.example), not declared
// in wrangler.jsonc, so `wrangler types` does not generate it. Augment Env here.
interface Env {
  ADMIN_TOKEN?: string;
  // Cache purge-on-overwrite for zones we control (see purge.ts). This is the
  // Worker secret (Zone → Cache Purge scope), so it isn't generated by
  // `wrangler types`; the CF_PURGE_ZONE_ID / CF_PURGE_HOSTS vars are.
  CF_PURGE_TOKEN?: string;
}
