/**
 * Shared Open Graph constants. Pages own their OG blocks (see BaseHead.astro),
 * but the brand-level values used verbatim across them live here so a rename
 * or asset move is a one-line change.
 *
 * og-home.png is generated by `node scripts/og/render-og.mjs`.
 */
export const OG_SITE_NAME = "uploads.sh";
export const OG_DEFAULT_IMAGE = "https://uploads.sh/og/home.png";

/**
 * OG image for a media page: images embed themselves, videos embed their
 * derived poster frame when one exists (posterUrl is only ever set for
 * videos), everything else falls back to the brand card. Shared by the /f/
 * file page and the gallery item page so the rule can't drift.
 */
export function ogImageFor(
  kind: string,
  url: string | null,
  posterUrl: string | null | undefined,
): string {
  if (kind === "image" && url) return url;
  return posterUrl ?? OG_DEFAULT_IMAGE;
}
