/**
 * Shared Open Graph constants. Pages own their OG blocks (see BaseHead.astro),
 * but the brand-level values used verbatim across them live here so a rename
 * or asset move is a one-line change.
 *
 * og-home.png is generated by `node scripts/og/render-og.mjs`.
 */
export const OG_SITE_NAME = "uploads.sh";
export const OG_DEFAULT_IMAGE = "https://uploads.sh/og/home.png";
